services:
  sh:
    pull_policy: build
    build:
      context: .
    volumes:
      - ./:/lang

  test:
    pull_policy: build
    build:
      context: .
    volumes:
      - ./:/lang
    entrypoint:
      - make
      - test

  emit:
    pull_policy: build
    build:
      context: .
    volumes:
      - ./:/lang
    entrypoint:
      - sandbox/emit.sh
      - sandbox/code.c
